---
title: The macroevolution of bipartite networks
short: Bipartite network macroevolution
keyword:
  - ecological networks
  - macroecoevolution
  - approximate Bayesian computation
date: 2017-06-22T00:00:00.000Z
abstract: |
  TODO
author:
  - family: Poisot
    given: Timothée
    affiliations:
      - 1
      - 2
      - 3
    email: timothee.poisot@umontreal.ca
    id: tp
    orcid: 0000-0002-0735-5184
  - family: Stouffer
    given: Daniel B.
    affiliations:
      - 1
    id: dbs
    orcid: 0000-0001-9436-9674
affiliation:
  - id: 1
    text: >-
      Centre for Integrative Ecology, School of Biological Sciences, University
      of Canterbury, Christchurch, New Zealand
  - id: 2
    text: 'Université de Montréal, Département de Sciences Biologiques'
  - id: 3
    text: Québec Centre for Biodiversity Sciences
cleveref: true
...
